name: Deploy Test with Action
 
on:
  push:
    branches: [main]
 
  workflow_dispatch:
 
permissions:
  contents: read
  packages: write
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Setup Bastion SSH
        uses: rishav2404/setup-bastion-ssh@v1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
 
          bastion-host: ${{ secrets.BASTION_HOST }}
          bastion-user: ${{ secrets.BASTION_USER }}
          bastion-port: ${{ secrets.BASTION_PORT }}
 
          bastion-known-host: ${{ secrets.BASTION_KNOWN_HOSTS }}
 
          server-host: ${{ secrets.TARGET_HOST }}
          server-user: ${{ secrets.TARGET_USER }}
 
          server-known-host: ${{ secrets.SERVER4_KNOWN_HOSTS }}
 
          strict-host-checking: "yes"
 
      - name: Execute deployment script
        run: |
          ssh target 'bash -lc "cd /opt/qcc-dfr && ./rishav.sh RishavStrict"'
