name: Deploy Application
 
on:

  push:

    branches: [main]
 
jobs:

  deploy:

    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout your code

        uses: actions/checkout@v6
 
      - name: Setup SSH

        uses: rishav2404/setup-bastion-ssh@v1

        with:

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
          bastion-host: ${{ secrets.BASTION_HOST }}

          bastion-user: ${{ secrets.BASTION_USER }}

          bastion-port: "9222"
 
          server-host: ${{ secrets.TARGET_HOST }}

          server-user: ${{ secrets.TARGET_USER }}
 
      - name: Perform SSH action

        run: |

          ssh target 'cd /xyz && ./deploy.sh'
 
